### ISSUE TITLE
Documentação: Criar História 5 e cenários

### ISSUE THREAD

**Issue by DiegoKremer** [Rafa2F/Alpha-Project#26]
Sendo um professor que deseja ensinar equações para os alunos
Posso inserir um arquivo de equações no sistema 
Para que o aluno possa estudar estas equações

Após a criação dos cenários, criar as issues de implementação de cada um deles.

**Comment by Rafa2F** [comment]
Historia 5 não é correspondente a mencionada, ela é sobre a explicação do passo a passo. Issue completa.
