### ISSUE TITLE
Armazenar as alterações feitas nos passos da resolução

### ISSUE THREAD

**Issue by DiegoKremer** [Rafa2F/Alpha-Project#29]
Armazenar o nome da operação, os valores alterados e o resultado da operação. Criar uma lista de Strings na classe Resolver em que cada método de operação. 

Exemplo: Método de soma
lista.add("Soma " + valorA + "+" + valorB + ";" + resultado);

**Comment by Rafa2F** [comment]
Esta sendo armazenada conforme a issue.
